services:
  hugo:
    build: ./hugo-docker
    command: "--baseURL \"${BASE_URL}\" -w"
    volumes:
      - ".:/usr/src/app"
    user: "${UID}:${GID}"
  nginx:
    image: 'nginx'
    restart: always
    ports:
      - "${PORT}:80"
    volumes:
      - "./public:${WWW_ROOT:-/usr/share/nginx/html}"
    depends_on:
      - hugo
