services:
  hugo:
    build: ./hugo-docker
    command: "--baseURL \"${BASE_URL}\""
    volumes:
      - ".:/usr/src/app"
    user: "${UID}:${GID}"
  nginx:
    image: 'nginx'
    restart: always
    ports:
      - "${PORT}:80"
    volumes:
      - "./public:/usr/share/nginx/html"
    depends_on:
      - hugo
