baseURL = 'https://example.org/'

disablePathToLower = true

enableGitInfo = true

enableRobotsTXT = true

languageCode = 'en-us'

pluralizeListTitles = false
pygmentsUseClasses = true
pygmentsCodeFences = true

title = 'My Documentation Site'

theme = 'hugo-geekdoc'

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]

[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"