baseURL = 'https://example.org/'
title = 'PGEtinker | The Docs'
theme = 'hugo-geekdoc'

# Required to get well formatted code blocks
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

defaultContentLanguage = "en"
languageCode = 'en-us'

[languages.en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10

[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode or when nesting shortcodes (e.g. img within
    # columns or tabs)
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
  tag = "tags"

[params]
  geekdocToC = 3
  geekdocNextPrev = true
  geekdocBreadcrumb = true
  geekdocSearch = true
  geekdocSearchShowParent = true

  # geekdocLegalNotice = "https://blog.example.com/legal"
  # geekdocPrivacyPolicy = "/privacy"

  geekdocAnchor = true
  geekdocAnchorCopy = true
  geekdocImageLazyLoading = true
  geekdocOverwriteHTMLBase = false
  geekdocDarkModeToggle = false

  geekdocDarkModeDim = false
  geekdocDarkModeCode = false

  geekdocBackToTop = true
  geekdocTagsToMenu = true
  
  # (Optional, default 'title') Configure how to sort file-tree menu entries. Possible options are 'title', 'linktitle',
  # 'date', 'publishdate', 'expirydate' or 'lastmod'. Every option can be used with a reverse modifier as well
  # e.g. 'title_reverse'.
  geekdocFileTreeSortBy = "title"


