baseURL = 'https://example.org/'

defaultContentLanguage = "en"

disablePathToLower = true

enableGitInfo = true

enableRobotsTXT = true

languageCode = 'en-us'

pluralizeListTitles = false
pygmentsUseClasses = true
pygmentsCodeFences = true

title = 'PGEtinker'

theme = 'hugo-geekdoc'

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]

[languages.en]
languageName = "English"
contentDir = "content/en"
weight = 10

[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"
