name: Command via SSH

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: test ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls scripts
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
        env:
          CI: true